version: '3.9'

services:
  treehole:
    image: shi2002/open_tree_hole_backend
    ports:
      - "80:80"
    restart: always
    environment:
      - SITE_NAME=
      - ALLOW_CONNECT_HOSTS=
      - EMAIL_WHITELIST=
      - DATABASE_HOST=db
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - SECRET_KEY=
      - REDIS_ADDRESS=redis://redis:6379

    depends_on:
      - db
      - redis

  db:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    restart: always

  redis:
    image: redis
    restart: always

  celery:
    image: shi2002/open_tree_hole_backend
    entrypoint: [ "pipenv", "run", "celery", "-A", "OpenTreeHole", "worker", "-l", "info" ]
    environment:
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_USE_TLS=
      - EMAIL_USE_SSL=
      - DEFAULT_FROM_EMAIL=
      - GITHUB_OWENER=
      - GITHUB_TOKEN=
      - GITHUB_REPO=
      - GITHUB_BRANCH=
      - REDIS_ADDRESS=redis://redis:6379
    restart: always
    depends_on:
      - redis
      - treehole

volumes:
  data: