# Generated by Django 3.2.5 on 2021-07-17 02:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('shadow_text', models.TextField(help_text='去除markdown关键字的文本，方便搜索')),
                ('anonyname', models.CharField(max_length=16)),
                ('reply_to', models.IntegerField(null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(db_index=True, default=0)),
                ('like_data', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('history', models.JSONField(default=list)),
                ('delete_reason', models.TextField(null=True)),
                ('folded', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('view', models.IntegerField(db_index=True, default=0, help_text='浏览量')),
                ('reply', models.IntegerField(db_index=True, default=-1, help_text='楼层数')),
                ('mapping', models.JSONField(default=dict, help_text='匿名到真实用户的对应')),
                ('division', models.ForeignKey(help_text='分区', on_delete=django.db.models.deletion.CASCADE, to='api.division')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('temperature', models.IntegerField(db_index=True, default=0, help_text='该标签下的主题帖数')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('dealed', models.BooleanField(db_index=True, default=False)),
                ('dealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floor')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hole')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=32)),
                ('permission', models.JSONField(default=api.models.default_permission)),
                ('favorites', models.ManyToManyField(blank=True, to='api.Hole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='floor',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hole'),
        ),
        migrations.AddField(
            model_name='floor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
