# Generated by Django 3.1.13 on 2021-10-14 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=150, unique=True)),
                ('joined_time', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=32)),
                ('permission', models.JSONField(default=api.models.default_permission)),
                ('config', models.JSONField(default=api.models.default_config)),
                ('push_notification_tokens', models.JSONField(default=api.models.default_push_notification_tokens)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(null=True)),
                ('pinned', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('shadow_text', models.TextField(default='')),
                ('anonyname', models.CharField(max_length=16)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(db_index=True, default=0)),
                ('like_data', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('history', models.JSONField(default=list)),
                ('fold', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('view', models.IntegerField(db_index=True, default=0, help_text='浏览量')),
                ('reply', models.IntegerField(db_index=True, default=-1, help_text='楼层数')),
                ('mapping', models.JSONField(default=dict, help_text='匿名到真实用户的对应')),
                ('division', models.ForeignKey(help_text='分区', on_delete=django.db.models.deletion.CASCADE, to='api.division')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cleartext', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('temperature', models.IntegerField(db_index=True, default=0, help_text='该标签下的主题帖数')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('dealed', models.BooleanField(db_index=True, default=False)),
                ('dealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floor')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hole')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('code', models.CharField(default='', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('has_read', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='floor',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hole'),
        ),
        migrations.AddField(
            model_name='floor',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='mentioned_by', to='api.Floor'),
        ),
        migrations.AddField(
            model_name='floor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='api.Hole'),
        ),
    ]
