# Generated by Django 3.2.7 on 2021-10-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='floor',
            name='mention',
            field=models.ManyToManyField(blank=True, related_name='_api_floor_mention_+', to='api.Floor'),
        ),
    ]
