# Generated by Django 3.2.5 on 2021-07-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='folded',
            new_name='fold',
        ),
    ]
