# Generated by Django 3.1.14 on 2022-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='special_tag',
            field=models.CharField(default='', max_length=16),
        ),
    ]
