# Generated by Django 3.2.7 on 2021-10-03 07:56

import django.db.models.deletion
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='config',
            field=models.JSONField(default=api.models.default_config),
        ),
        migrations.AlterField(
            model_name='floor',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.floor'),
        ),
    ]
