# Generated by Django 3.1.13 on 2021-10-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredEmail',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
