# Generated by Django 3.1.13 on 2021-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='black', max_length=32),
        ),
    ]
