# Generated by Django 3.2.5 on 2021-07-17 14:01
import time
from datetime import datetime, timezone

from django.db import migrations
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password


def init_division(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Division = apps.get_model('api', 'Division')
    Division.objects.create(name='树洞', description='论坛板块，进行一般性的讨论')
    Division.objects.create(name='表白墙', description='道出心声')
    Division.objects.create(name='跳蚤市场', description='二手交易及广告')


def init_admin(apps, schema_editor):
    User.objects.create_user(username='admin', password=make_password('random password'))


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_division),
        migrations.RunPython(init_admin),
    ]
