# Generated by Django 3.1.13 on 2021-11-28 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
