# Generated by Django 3.2.7 on 2021-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_rename_folded_floor_fold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
