# Generated by Django 3.1.13 on 2021-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_remove_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
