# Generated by Django 3.1.14 on 2022-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_olduserfavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='hidden',
            field=models.BooleanField(default=False, help_text='帖子是否隐藏'),
        ),
    ]
