# Generated by Django 3.2.7 on 2021-09-28 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20210928_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_user',
            new_name='user',
        ),
    ]
