# Generated by Django 3.2.7 on 2021-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_floor_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='shadow_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='api.Hole'),
        ),
    ]
