# Generated by Django 3.1.14 on 2022-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_hole_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('dau', models.IntegerField(default=0)),
                ('mau', models.IntegerField(default=0)),
            ],
        ),
    ]
