# Generated by Django 3.2.7 on 2021-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20211004_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
