# Generated by Django 3.2.7 on 2021-10-04 15:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211004_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notification_tokens',
            field=models.JSONField(default=api.models.default_push_notification_tokens),
        ),
    ]
