# Generated by Django 3.1.14 on 2022-01-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20220115_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='device_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
