# Generated by Django 3.1.14 on 2022-01-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_auto_20220122_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
