# Generated by Django 3.2.7 on 2021-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_user_push_notification_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='pinned',
            field=models.JSONField(default=list),
        ),
    ]
