# Generated by Django 3.1.14 on 2022-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20220123_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(default='树洞', max_length=32, unique=True),
        ),
    ]
