# Generated by Django 3.1.14 on 2022-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_auto_20220123_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='storey',
            field=models.IntegerField(default=0),
        ),
    ]
