# Generated by Django 3.1.13 on 2021-10-12 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20211011_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_encrypted',
            new_name='email',
        ),
    ]
