# Generated by Django 3.1.14 on 2022-02-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_floor_storey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
