name: dev build

on:
  push:
    branches:
      - auth
  pull_request:
    branches:
      - dev

env:
  APP_NAME: open_tree_hole_backend
  TEST_TAG: app:test

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Build and export to Docker
      #        uses: docker/build-push-action@v2
      #        with:
      #          load: true
      #          tags: ${{ env.TEST_TAG }}
      #      - name: Test
      #        run: docker run --rm ${{ env.TEST_TAG }} test
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME}}:dev