name: Production Build
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}_backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}_backend:master
          build-args: |
            SERVICE_NAME=${{ inputs.service_name }}

      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@master
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Aliyun ACR
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ inputs.service_name }}_backend:latest
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ inputs.service_name }}_backend:master
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ inputs.service_name }}:latest
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ inputs.service_name }}:master
          build-args: |
            SERVICE_NAME=${{ inputs.service_name }}
